server:
  port: 8080


management:
  observations:
    http:
      server:
        requests:
          write-traceresponse: true
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: gradle-demo

azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHT_KEY:00000000-0000-0000-0000-000000000000}
